#!/bin/bash

set -ue

# const
# ----------
readonly DOT_PATH=~/dotfiles
readonly REMOTE_URL="https://github.com/wurzeit/dotfiles.git"

# colors
if which tput >/dev/null 2>&1; then
  ncolors=$(tput colors)
fi
if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
  RED="$(tput setaf 1)"
  GREEN="$(tput setaf 2)"
  YELLOW="$(tput setaf 3)"
  BLUE="$(tput setaf 4)"
  BOLD="$(tput bold)"
  NORMAL="$(tput sgr0)"
else
  RED=""
  GREEN=""
  YELLOW=""
  BLUE=""
  BOLD=""
  NORMAL=""
fi

# function
# ----------
has() {
  type "$1" > /dev/null 2>&1
}

dotfiles() {
  echo $BLUE
  cat <<\EOF

      _       _    __ _ _           
   __| | ___ | |_ / _(_) | ___  ___ 
  / _` |/ _ \| __| |_| | |/ _ \/ __|
 | (_| | (_) | |_|  _| | |  __/\__ \
(_)__,_|\___/ \__|_| |_|_|\___||___/
                                    

EOF
  echo $NORMAL
}

usage() {
  echo $YELLOW
  cat <<\EOF
Commands:
  init (download dotfiles)
  quit
EOF
  echo $NORMAL
}

download() {
  cd $HOME

  # dotfiles
  if [ ! -d $DOT_PATH ]; then
    echo "Downloading dotfiles..."
    if has "git"; then
      git clone --recursive $REMOTE_URL $DOT_PATH
    else
      echo "${RED}Please install git.$NORMAL"
      exit 1
    fi
    if [ $? = 0 ]; then
      echo "${GREEN}Successfully downloaded dotfiles.$NORMAL"
    else
      echo "${RED}An unexpected error occurred when trying to install git.$NORMAL"
      exit 1
    fi
  else
    echo "${BOLD}dotfiles already exists.$NORMAL"
  fi
}


main() {
  usage
  echo -n "${BOLD}command: $NORMAL"
  read command
  case $command in
    init)
      download
      main
      ;;
    quit)
      echo "bye!"
      exit 0
      ;;
    *)
      echo "${RED}bootstrap: command not found.$NORMAL"
      main
      ;;
    esac
}

# main
# ----------
dotfiles
main

exit 0
