local function load_options()
    local global_local = {
        termguicolors = true,
        errorbells = true,
        visialbell = true,
        hidden = true,
        fileformats = "unix,mac,dos",
        magic = true,
        virtualedit = "block",
        encoding = "utf-8",
        viewoptions = "folds,cursor,curdir,slash,unix",
        sessionoptions = "curdir,help,tabpages,winsize",
        clipboard = "unnamedplus",
        wildignorecase = true,
        wildignore = ".git,.hg,.svn,*.pyc,*.o,*.out,*.jpg,*.jpeg,*.png,*.gif,*.zip,**/tmp/**,*.DS_Store,**/node_modules/**,**/bower_modules/**",
        swapfile = false,
        history = 2000,
        shada = "!,'300,<50,@100,s10,h",
        backupskip = "/tmp/*,$TMPDIR/*,$TMP/*,$TEMP/*,*/shm/*,/private/var/*,.vault.vim",
        smarttab = true,
        shiftround = true,
        updatetime = 100,
        redrawtime = 1500,
        ignorecase = true,
        smartcase = true,
        infercase = true,
        incsearch = true,
        hlsearch = true,
        wrapscan = true,
        inccommand = "split",
        number = true,
        relativenumber = true,
        showmatch = 1,
        expandtab = true,
        tabstop = 4,
        title = true,
        scrolloff = 7,
        sidescrolloff = 5,
        display = "lastline",
        pumheight = 10,
        autoindent = true,
        smartindent = true,
        cindent = true,
        showcmd = true,
        list = true,
        listchars = "tab:»-,trail:-,eol:↲,extends:»,precedes:«,nbsp:%",
        backup = true,
        swapfile = true,
        undofile = true,
        wildmenu = true,
        ambiwidth = "single",
        winblend = 20,
        pumblend = 20,
        shell = "fish",
        cmdheight = 0,
    }
	for name, value in pairs(global_local) do
		vim.o[name] = value
	end
end

load_options()
