require('base')
require('map')
require('plugins')
require('color')
require('autopair')
require('autotag')
require('statusline')
require('ts')
require('tele')
require('lsp')
require('bl')
require('saga')
require('nullls')
require('pret')
require('gsign')

print('init.lua loaded')
